_target_: "src.model.SWAE"
encoder:
  _target_: "src.model.encoders_decoders.EncoderShallow"
  filters: [32,64,128,256,512]
  input_dim: ${preproc.channels}
decoder:
  _target_: "src.model.encoders_decoders.DecoderShallow"
  filters: [512,256,128,64,32]
  output_dim: ${preproc.channels}
latent: 256
loss_scaling:
  mse_loss: 1.0
  swae_loss: 0.5
wasserstein_deg: 2
num_projections: 50
reg_weight: 5.0
